// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: home_station

#ifndef _HOME_STATION_UI_H
#define _HOME_STATION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_station_panel;
extern lv_obj_t *ui_station2;
extern lv_obj_t *ui_onglet;
extern lv_obj_t *ui_piece;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_temp_ind;
extern lv_obj_t *ui_temp_image;
extern lv_obj_t *ui_humidity;
extern lv_obj_t *ui_humidity_ind;
extern lv_obj_t *ui_humidity_image;
extern lv_obj_t *ui_altitude;
extern lv_obj_t *ui_altitude_ind;
extern lv_obj_t *ui_altitude_image;
extern lv_obj_t *ui_status;
extern lv_obj_t *ui_status_dot2;
extern lv_obj_t *ui_station1;
extern lv_obj_t *ui_onglet1;
extern lv_obj_t *ui_piece1;
extern lv_obj_t *ui_temp1;
extern lv_obj_t *ui_temp_ind1;
extern lv_obj_t *ui_temp_image1;
extern lv_obj_t *ui_humidity1;
extern lv_obj_t *ui_humidity_ind1;
extern lv_obj_t *ui_humidity_image1;
extern lv_obj_t *ui_altitude1;
extern lv_obj_t *ui_altitude_ind1;
extern lv_obj_t *ui_altitude_image1;
extern lv_obj_t *ui_status1;
extern lv_obj_t *ui_status_dot;
extern lv_obj_t *ui_station3;
extern lv_obj_t *ui_onglet2;
extern lv_obj_t *ui_piece2;
extern lv_obj_t *ui_temp2;
extern lv_obj_t *ui_temp_ind2;
extern lv_obj_t *ui_temp_image2;
extern lv_obj_t *ui_humidity2;
extern lv_obj_t *ui_humidity_ind2;
extern lv_obj_t *ui_humidity_image2;
extern lv_obj_t *ui_altitude2;
extern lv_obj_t *ui_altitude_ind2;
extern lv_obj_t *ui_altitude_image2;
extern lv_obj_t *ui_status2;
extern lv_obj_t *ui_status_dot1;
extern lv_obj_t *ui_home_panel;
extern lv_obj_t *ui_meteo_future;
extern lv_obj_t *ui_heure_date;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_meteo_jour;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_meteo_next;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_meteo_next1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_meteo_next2;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_meteo_next3;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_thermometer_5545481_png);   // assets/thermometer_5545481.png
LV_IMG_DECLARE( ui_img_humidity_4567750_png);   // assets/humidity_4567750.png
LV_IMG_DECLARE( ui_img_851468207);   // assets/speedometer_7072719-2.png
LV_IMG_DECLARE( ui_img_01d_png);   // assets/01d.png
LV_IMG_DECLARE( ui_img_09d_png);   // assets/09d.png
LV_IMG_DECLARE( ui_img_09n_png);   // assets/09n.png
LV_IMG_DECLARE( ui_img_13d_png);   // assets/13d.png
LV_IMG_DECLARE( ui_img_mountain_3975474_png);   // assets/mountain_3975474.png
LV_IMG_DECLARE( ui_img_01n_png);   // assets/01n.png
LV_IMG_DECLARE( ui_img_02d_png);   // assets/02d.png
LV_IMG_DECLARE( ui_img_02n_png);   // assets/02n.png
LV_IMG_DECLARE( ui_img_03d_png);   // assets/03d.png
LV_IMG_DECLARE( ui_img_03n_png);   // assets/03n.png
LV_IMG_DECLARE( ui_img_04d_png);   // assets/04d.png
LV_IMG_DECLARE( ui_img_04n_png);   // assets/04n.png
LV_IMG_DECLARE( ui_img_10d_png);   // assets/10d.png
LV_IMG_DECLARE( ui_img_10n_png);   // assets/10n.png
LV_IMG_DECLARE( ui_img_11d_png);   // assets/11d.png
LV_IMG_DECLARE( ui_img_11n_png);   // assets/11n.png
LV_IMG_DECLARE( ui_img_13n_png);   // assets/13n.png
LV_IMG_DECLARE( ui_img_50d_png);   // assets/50d.png
LV_IMG_DECLARE( ui_img_50n_png);   // assets/50n.png

// FONTS
LV_FONT_DECLARE( ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
