// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: home_station

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_station_panel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_station_panel, 800);
lv_obj_set_height( ui_station_panel, 200);
lv_obj_set_x( ui_station_panel, 0 );
lv_obj_set_y( ui_station_panel, 140 );
lv_obj_set_align( ui_station_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_station_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_station_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_station2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_station2, 250);
lv_obj_set_height( ui_station2, 200);
lv_obj_set_x( ui_station2, 0 );
lv_obj_set_y( ui_station2, 141 );
lv_obj_set_align( ui_station2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_station2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_station2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_station2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_station2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_white);

ui_onglet = lv_obj_create(ui_station2);
lv_obj_set_width( ui_onglet, 250);
lv_obj_set_height( ui_onglet, 50);
lv_obj_set_x( ui_onglet, 0 );
lv_obj_set_y( ui_onglet, -75 );
lv_obj_set_align( ui_onglet, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_onglet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_onglet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_onglet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_onglet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_piece = lv_label_create(ui_station2);
lv_obj_set_width( ui_piece, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_piece, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_piece, -40 );
lv_obj_set_y( ui_piece, -75 );
lv_obj_set_align( ui_piece, LV_ALIGN_CENTER );
lv_label_set_text(ui_piece,"Chambre Maloe");
lv_obj_set_style_text_color(ui_piece, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_piece, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_piece, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_piece, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp = lv_label_create(ui_station2);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -70 );
lv_obj_set_y( ui_temp, -25 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp,"77.7");
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0x0A6EDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_ind = lv_label_create(ui_station2);
lv_obj_set_width( ui_temp_ind, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp_ind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_ind, 3 );
lv_obj_set_y( ui_temp_ind, -23 );
lv_obj_set_align( ui_temp_ind, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_ind,"°c");
lv_obj_set_style_text_font(ui_temp_ind, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_image = lv_img_create(ui_station2);
lv_img_set_src(ui_temp_image, &ui_img_thermometer_5545481_png);
lv_obj_set_width( ui_temp_image, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_temp_image, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_temp_image, 95 );
lv_obj_set_y( ui_temp_image, -23 );
lv_obj_set_align( ui_temp_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_temp_image, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_temp_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_temp_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_temp_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_humidity = lv_label_create(ui_station2);
lv_obj_set_width( ui_humidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity, -90 );
lv_obj_set_y( ui_humidity, 24 );
lv_obj_set_align( ui_humidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity,"80");
lv_obj_set_style_text_font(ui_humidity, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_ind = lv_label_create(ui_station2);
lv_obj_set_width( ui_humidity_ind, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity_ind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_ind, -48 );
lv_obj_set_y( ui_humidity_ind, 24 );
lv_obj_set_align( ui_humidity_ind, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_ind,"%");
lv_obj_set_style_text_font(ui_humidity_ind, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_image = lv_img_create(ui_station2);
lv_img_set_src(ui_humidity_image, &ui_img_humidity_4567750_png);
lv_obj_set_width( ui_humidity_image, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_humidity_image, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_humidity_image, 95 );
lv_obj_set_y( ui_humidity_image, 24 );
lv_obj_set_align( ui_humidity_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_humidity_image, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_humidity_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_humidity_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_humidity_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_altitude = lv_label_create(ui_station2);
lv_obj_set_width( ui_altitude, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude, -83 );
lv_obj_set_y( ui_altitude, 70 );
lv_obj_set_align( ui_altitude, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude,"1100");
lv_obj_set_style_text_font(ui_altitude, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_ind = lv_label_create(ui_station2);
lv_obj_set_width( ui_altitude_ind, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude_ind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude_ind, -23 );
lv_obj_set_y( ui_altitude_ind, 70 );
lv_obj_set_align( ui_altitude_ind, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude_ind,"hPa");
lv_obj_set_style_text_font(ui_altitude_ind, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_image = lv_img_create(ui_station2);
lv_img_set_src(ui_altitude_image, &ui_img_851468207);
lv_obj_set_width( ui_altitude_image, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_altitude_image, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_altitude_image, 95 );
lv_obj_set_y( ui_altitude_image, 70 );
lv_obj_set_align( ui_altitude_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_altitude_image, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_altitude_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_altitude_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_altitude_image, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_status = lv_spinner_create(ui_station2,1000,90);
lv_obj_set_width( ui_status, 32);
lv_obj_set_height( ui_status, 32);
lv_obj_set_x( ui_status, 95 );
lv_obj_set_y( ui_status, -74 );
lv_obj_set_align( ui_status, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status, LV_OBJ_FLAG_CLICKABLE );    /// Flags
ui_object_set_themeable_style_property(ui_status, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_status, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_white);
lv_obj_set_style_arc_width(ui_status, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status, lv_color_hex(0x00FF2E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_status, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_dot2 = lv_obj_create(ui_station2);
lv_obj_set_width( ui_status_dot2, 16);
lv_obj_set_height( ui_status_dot2, 16);
lv_obj_set_x( ui_status_dot2, 95 );
lv_obj_set_y( ui_status_dot2, -77 );
lv_obj_set_align( ui_status_dot2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_dot2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_status_dot2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_dot2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_dot2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_station1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_station1, 250);
lv_obj_set_height( ui_station1, 200);
lv_obj_set_x( ui_station1, -270 );
lv_obj_set_y( ui_station1, 141 );
lv_obj_set_align( ui_station1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_station1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_station1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_station1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_station1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_white);
lv_obj_set_style_shadow_color(ui_station1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_station1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_station1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_station1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_station1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_station1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_onglet1 = lv_obj_create(ui_station1);
lv_obj_set_width( ui_onglet1, 250);
lv_obj_set_height( ui_onglet1, 50);
lv_obj_set_x( ui_onglet1, 0 );
lv_obj_set_y( ui_onglet1, -75 );
lv_obj_set_align( ui_onglet1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_onglet1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_onglet1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_onglet1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_onglet1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_piece1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_piece1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_piece1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_piece1, -93 );
lv_obj_set_y( ui_piece1, -75 );
lv_obj_set_align( ui_piece1, LV_ALIGN_CENTER );
lv_label_set_text(ui_piece1,"Salon");
lv_obj_set_style_text_color(ui_piece1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_piece1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_piece1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_piece1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_temp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp1, -70 );
lv_obj_set_y( ui_temp1, -25 );
lv_obj_set_align( ui_temp1, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp1,"77.7");
lv_obj_set_style_text_color(ui_temp1, lv_color_hex(0x0ADE2A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_ind1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_temp_ind1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp_ind1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_ind1, 2 );
lv_obj_set_y( ui_temp_ind1, -23 );
lv_obj_set_align( ui_temp_ind1, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_ind1,"°c");
lv_obj_set_style_text_font(ui_temp_ind1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_image1 = lv_img_create(ui_station1);
lv_img_set_src(ui_temp_image1, &ui_img_thermometer_5545481_png);
lv_obj_set_width( ui_temp_image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_temp_image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_temp_image1, 95 );
lv_obj_set_y( ui_temp_image1, -23 );
lv_obj_set_align( ui_temp_image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_temp_image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_temp_image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_temp_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_temp_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_humidity1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_humidity1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity1, -90 );
lv_obj_set_y( ui_humidity1, 24 );
lv_obj_set_align( ui_humidity1, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity1,"80");
lv_obj_set_style_text_font(ui_humidity1, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_ind1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_humidity_ind1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity_ind1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_ind1, -48 );
lv_obj_set_y( ui_humidity_ind1, 24 );
lv_obj_set_align( ui_humidity_ind1, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_ind1,"%");
lv_obj_set_style_text_font(ui_humidity_ind1, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_image1 = lv_img_create(ui_station1);
lv_img_set_src(ui_humidity_image1, &ui_img_humidity_4567750_png);
lv_obj_set_width( ui_humidity_image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_humidity_image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_humidity_image1, 95 );
lv_obj_set_y( ui_humidity_image1, 24 );
lv_obj_set_align( ui_humidity_image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_humidity_image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_humidity_image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_humidity_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_humidity_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_altitude1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_altitude1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude1, -83 );
lv_obj_set_y( ui_altitude1, 70 );
lv_obj_set_align( ui_altitude1, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude1,"1100");
lv_obj_set_style_text_font(ui_altitude1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_ind1 = lv_label_create(ui_station1);
lv_obj_set_width( ui_altitude_ind1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude_ind1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude_ind1, -23 );
lv_obj_set_y( ui_altitude_ind1, 70 );
lv_obj_set_align( ui_altitude_ind1, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude_ind1,"hPa");
lv_obj_set_style_text_font(ui_altitude_ind1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_image1 = lv_img_create(ui_station1);
lv_img_set_src(ui_altitude_image1, &ui_img_851468207);
lv_obj_set_width( ui_altitude_image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_altitude_image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_altitude_image1, 95 );
lv_obj_set_y( ui_altitude_image1, 70 );
lv_obj_set_align( ui_altitude_image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_altitude_image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_altitude_image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_altitude_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_altitude_image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_status1 = lv_spinner_create(ui_station1,1000,90);
lv_obj_set_width( ui_status1, 32);
lv_obj_set_height( ui_status1, 32);
lv_obj_set_x( ui_status1, 95 );
lv_obj_set_y( ui_status1, -74 );
lv_obj_set_align( ui_status1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
ui_object_set_themeable_style_property(ui_status1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_status1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_white);
lv_obj_set_style_arc_width(ui_status1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status1, lv_color_hex(0x00FF2E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_status1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status1, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_dot = lv_obj_create(ui_station1);
lv_obj_set_width( ui_status_dot, 16);
lv_obj_set_height( ui_status_dot, 16);
lv_obj_set_x( ui_status_dot, 95 );
lv_obj_set_y( ui_status_dot, -77 );
lv_obj_set_align( ui_status_dot, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_dot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_status_dot, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_dot, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_dot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_station3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_station3, 250);
lv_obj_set_height( ui_station3, 200);
lv_obj_set_x( ui_station3, 270 );
lv_obj_set_y( ui_station3, 141 );
lv_obj_set_align( ui_station3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_station3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_station3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_station3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_station3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_white);

ui_onglet2 = lv_obj_create(ui_station3);
lv_obj_set_width( ui_onglet2, 250);
lv_obj_set_height( ui_onglet2, 50);
lv_obj_set_x( ui_onglet2, 0 );
lv_obj_set_y( ui_onglet2, -75 );
lv_obj_set_align( ui_onglet2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_onglet2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_onglet2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_onglet2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_onglet2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_piece2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_piece2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_piece2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_piece2, -23 );
lv_obj_set_y( ui_piece2, -75 );
lv_obj_set_align( ui_piece2, LV_ALIGN_CENTER );
lv_label_set_text(ui_piece2,"Chambre parentale");
lv_obj_set_style_text_color(ui_piece2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_piece2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_piece2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_piece2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_temp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp2, -69 );
lv_obj_set_y( ui_temp2, -25 );
lv_obj_set_align( ui_temp2, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp2,"77.7");
lv_obj_set_style_text_color(ui_temp2, lv_color_hex(0xC9DE0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_ind2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_temp_ind2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp_ind2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_ind2, 5 );
lv_obj_set_y( ui_temp_ind2, -23 );
lv_obj_set_align( ui_temp_ind2, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_ind2,"°c");
lv_obj_set_style_text_font(ui_temp_ind2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_image2 = lv_img_create(ui_station3);
lv_img_set_src(ui_temp_image2, &ui_img_thermometer_5545481_png);
lv_obj_set_width( ui_temp_image2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_temp_image2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_temp_image2, 95 );
lv_obj_set_y( ui_temp_image2, -23 );
lv_obj_set_align( ui_temp_image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_temp_image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_temp_image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_temp_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_temp_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_humidity2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_humidity2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity2, -90 );
lv_obj_set_y( ui_humidity2, 24 );
lv_obj_set_align( ui_humidity2, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity2,"80");
lv_obj_set_style_text_font(ui_humidity2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_ind2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_humidity_ind2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity_ind2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_ind2, -48 );
lv_obj_set_y( ui_humidity_ind2, 24 );
lv_obj_set_align( ui_humidity_ind2, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_ind2,"%");
lv_obj_set_style_text_font(ui_humidity_ind2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_image2 = lv_img_create(ui_station3);
lv_img_set_src(ui_humidity_image2, &ui_img_humidity_4567750_png);
lv_obj_set_width( ui_humidity_image2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_humidity_image2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_humidity_image2, 95 );
lv_obj_set_y( ui_humidity_image2, 24 );
lv_obj_set_align( ui_humidity_image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_humidity_image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_humidity_image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_humidity_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_humidity_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_altitude2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_altitude2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude2, -83 );
lv_obj_set_y( ui_altitude2, 70 );
lv_obj_set_align( ui_altitude2, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude2,"1100");
lv_obj_set_style_text_font(ui_altitude2, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_ind2 = lv_label_create(ui_station3);
lv_obj_set_width( ui_altitude_ind2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_altitude_ind2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_altitude_ind2, -23 );
lv_obj_set_y( ui_altitude_ind2, 70 );
lv_obj_set_align( ui_altitude_ind2, LV_ALIGN_CENTER );
lv_label_set_text(ui_altitude_ind2,"hPa");
lv_obj_set_style_text_font(ui_altitude_ind2, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_altitude_image2 = lv_img_create(ui_station3);
lv_img_set_src(ui_altitude_image2, &ui_img_851468207);
lv_obj_set_width( ui_altitude_image2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_altitude_image2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_altitude_image2, 95 );
lv_obj_set_y( ui_altitude_image2, 70 );
lv_obj_set_align( ui_altitude_image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_altitude_image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_altitude_image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_altitude_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_altitude_image2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_white);

ui_status2 = lv_spinner_create(ui_station3,1000,90);
lv_obj_set_width( ui_status2, 32);
lv_obj_set_height( ui_status2, 32);
lv_obj_set_x( ui_status2, 95 );
lv_obj_set_y( ui_status2, -74 );
lv_obj_set_align( ui_status2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_status2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
ui_object_set_themeable_style_property(ui_status2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_status2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_white);
lv_obj_set_style_arc_width(ui_status2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_status2, lv_color_hex(0x00FF2E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_status2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_status2, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_status2, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_status_dot1 = lv_obj_create(ui_station3);
lv_obj_set_width( ui_status_dot1, 16);
lv_obj_set_height( ui_status_dot1, 16);
lv_obj_set_x( ui_status_dot1, 95 );
lv_obj_set_y( ui_status_dot1, -77 );
lv_obj_set_align( ui_status_dot1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_status_dot1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_status_dot1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_status_dot1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_status_dot1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_home_panel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_home_panel, 800);
lv_obj_set_height( ui_home_panel, 280);
lv_obj_set_x( ui_home_panel, -2 );
lv_obj_set_y( ui_home_panel, -99 );
lv_obj_set_align( ui_home_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_home_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_future = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_future, 395);
lv_obj_set_height( ui_meteo_future, 270);
lv_obj_set_x( ui_meteo_future, 198 );
lv_obj_set_y( ui_meteo_future, -100 );
lv_obj_set_align( ui_meteo_future, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_future, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_meteo_future, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_meteo_future, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_meteo_future, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_meteo_future, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_meteo_future, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_meteo_future, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_meteo_future, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_meteo_future, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heure_date = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_heure_date, 395);
lv_obj_set_height( ui_heure_date, 150);
lv_obj_set_x( ui_heure_date, -199 );
lv_obj_set_y( ui_heure_date, -159 );
lv_obj_set_align( ui_heure_date, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_heure_date, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_heure_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_heure_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_heure_date);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -99 );
lv_obj_set_y( ui_Label5, -10 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"22");
lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_heure_date);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 2 );
lv_obj_set_y( ui_Label1, -32 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,":");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_heure_date);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 2 );
lv_obj_set_y( ui_Label4, 57 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Jeudi 16 Janvier");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_heure_date);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 103 );
lv_obj_set_y( ui_Label2, -8 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"22");
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_jour = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_jour, 395);
lv_obj_set_height( ui_meteo_jour, 117);
lv_obj_set_x( ui_meteo_jour, -199 );
lv_obj_set_y( ui_meteo_jour, -23 );
lv_obj_set_align( ui_meteo_jour, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_jour, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_meteo_jour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_meteo_jour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_meteo_jour);
lv_img_set_src(ui_Image1, &ui_img_01d_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image1, -73 );
lv_obj_set_y( ui_Image1, -3 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_meteo_jour);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -14 );
lv_obj_set_y( ui_Label3, -41 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Toulouse, Haute Garonne");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_meteo_jour);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -10 );
lv_obj_set_y( ui_Label7, 38 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"partiellement nuageux");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_meteo_jour);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 41 );
lv_obj_set_y( ui_Label6, -3 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"22");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_meteo_jour);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 85 );
lv_obj_set_y( ui_Label20, -3 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"°c");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_next = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_next, 95);
lv_obj_set_height( ui_meteo_next, 250);
lv_obj_set_x( ui_meteo_next, 53 );
lv_obj_set_y( ui_meteo_next, -101 );
lv_obj_set_align( ui_meteo_next, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_next, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_meteo_next);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -2 );
lv_obj_set_y( ui_Label8, -99 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Ven");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_meteo_next);
lv_img_set_src(ui_Image2, &ui_img_01d_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image2, -3 );
lv_obj_set_y( ui_Image2, 32 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_meteo_next);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -1 );
lv_obj_set_y( ui_Label9, -39 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"9°c");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_meteo_next);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -1 );
lv_obj_set_y( ui_Label10, 101 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"0 / 5 °c");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_next1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_next1, 95);
lv_obj_set_height( ui_meteo_next1, 250);
lv_obj_set_x( ui_meteo_next1, 150 );
lv_obj_set_y( ui_meteo_next1, -102 );
lv_obj_set_align( ui_meteo_next1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_next1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_meteo_next1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -2 );
lv_obj_set_y( ui_Label11, -99 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Sam");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_meteo_next1);
lv_img_set_src(ui_Image3, &ui_img_09d_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image3, -3 );
lv_obj_set_y( ui_Image3, 32 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_meteo_next1);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -1 );
lv_obj_set_y( ui_Label12, -39 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"9°c");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_meteo_next1);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -1 );
lv_obj_set_y( ui_Label13, 101 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"0 / 5 °c");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_next2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_next2, 95);
lv_obj_set_height( ui_meteo_next2, 250);
lv_obj_set_x( ui_meteo_next2, 248 );
lv_obj_set_y( ui_meteo_next2, -101 );
lv_obj_set_align( ui_meteo_next2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_next2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_meteo_next2);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -2 );
lv_obj_set_y( ui_Label14, -99 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"Dim");
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_meteo_next2);
lv_img_set_src(ui_Image4, &ui_img_09n_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image4, -3 );
lv_obj_set_y( ui_Image4, 32 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_meteo_next2);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -1 );
lv_obj_set_y( ui_Label15, -39 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"9°c");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_meteo_next2);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -1 );
lv_obj_set_y( ui_Label16, 101 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"0 / 5 °c");
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meteo_next3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_meteo_next3, 95);
lv_obj_set_height( ui_meteo_next3, 250);
lv_obj_set_x( ui_meteo_next3, 345 );
lv_obj_set_y( ui_meteo_next3, -101 );
lv_obj_set_align( ui_meteo_next3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_meteo_next3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_meteo_next3);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -2 );
lv_obj_set_y( ui_Label17, -99 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Lun");
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_meteo_next3);
lv_img_set_src(ui_Image5, &ui_img_13d_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image5, -3 );
lv_obj_set_y( ui_Image5, 32 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_meteo_next3);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -1 );
lv_obj_set_y( ui_Label18, -39 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"9°c");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_meteo_next3);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, -1 );
lv_obj_set_y( ui_Label19, 101 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"0 / 5 °c");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);


}
