// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: home_station

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_station_panel;
lv_obj_t *ui_station2;
lv_obj_t *ui_onglet;
lv_obj_t *ui_piece;
lv_obj_t *ui_temp;
lv_obj_t *ui_temp_ind;
lv_obj_t *ui_temp_image;
lv_obj_t *ui_humidity;
lv_obj_t *ui_humidity_ind;
lv_obj_t *ui_humidity_image;
lv_obj_t *ui_altitude;
lv_obj_t *ui_altitude_ind;
lv_obj_t *ui_altitude_image;
lv_obj_t *ui_status;
lv_obj_t *ui_status_dot2;
lv_obj_t *ui_station1;
lv_obj_t *ui_onglet1;
lv_obj_t *ui_piece1;
lv_obj_t *ui_temp1;
lv_obj_t *ui_temp_ind1;
lv_obj_t *ui_temp_image1;
lv_obj_t *ui_humidity1;
lv_obj_t *ui_humidity_ind1;
lv_obj_t *ui_humidity_image1;
lv_obj_t *ui_altitude1;
lv_obj_t *ui_altitude_ind1;
lv_obj_t *ui_altitude_image1;
lv_obj_t *ui_status1;
lv_obj_t *ui_status_dot;
lv_obj_t *ui_station3;
lv_obj_t *ui_onglet2;
lv_obj_t *ui_piece2;
lv_obj_t *ui_temp2;
lv_obj_t *ui_temp_ind2;
lv_obj_t *ui_temp_image2;
lv_obj_t *ui_humidity2;
lv_obj_t *ui_humidity_ind2;
lv_obj_t *ui_humidity_image2;
lv_obj_t *ui_altitude2;
lv_obj_t *ui_altitude_ind2;
lv_obj_t *ui_altitude_image2;
lv_obj_t *ui_status2;
lv_obj_t *ui_status_dot1;
lv_obj_t *ui_home_panel;
lv_obj_t *ui_meteo_future;
lv_obj_t *ui_heure_date;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label2;
lv_obj_t *ui_meteo_jour;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label20;
lv_obj_t *ui_meteo_next;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_meteo_next1;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_meteo_next2;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui_meteo_next3;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_humidity_[1] = {&ui_img_humidity_4567750_png};
const lv_img_dsc_t *ui_imgset_mountain_[1] = {&ui_img_mountain_3975474_png};
const lv_img_dsc_t *ui_imgset_thermometer_[1] = {&ui_img_thermometer_5545481_png};
const lv_img_dsc_t *ui_imgset_1736156714[1] = {&ui_img_851468207};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
